# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "14df4a60f16290439acf4771c0358384"
name = "section demo"
handle = "section-demo-1"
application_url = "https://surrounded-lp-alice-simply.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "code-with-tj.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_products,write_themes"

[auth]
redirect_urls = [
  "https://surrounded-lp-alice-simply.trycloudflare.com/auth/callback",
  "https://surrounded-lp-alice-simply.trycloudflare.com/auth/shopify/callback",
  "https://surrounded-lp-alice-simply.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
